
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int LT = 11;
  public static final int KW_PRINT = 27;
  public static final int PLUS = 5;
  public static final int KW_IF = 23;
  public static final int RBRACE = 18;
  public static final int RPAREN = 16;
  public static final int SEMI = 2;
  public static final int LBRACE = 17;
  public static final int LPAREN = 15;
  public static final int GT = 12;
  public static final int ID = 31;
  public static final int LE = 13;
  public static final int COMMA = 3;
  public static final int EOF = 0;
  public static final int KW_WHILE = 25;
  public static final int DIV = 8;
  public static final int STR_LIT = 30;
  public static final int KW_RETURN = 26;
  public static final int GE = 14;
  public static final int MINUS = 6;
  public static final int error = 1;
  public static final int KW_VOID = 22;
  public static final int ASSIGN = 4;
  public static final int EQ = 9;
  public static final int INT_LIT = 28;
  public static final int FLOAT_LIT = 29;
  public static final int NEQ = 10;
  public static final int KW_ELSE = 24;
  public static final int KW_STRING = 21;
  public static final int KW_FLOAT = 20;
  public static final int KW_INT = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "COMMA",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "KW_INT",
  "KW_FLOAT",
  "KW_STRING",
  "KW_VOID",
  "KW_IF",
  "KW_ELSE",
  "KW_WHILE",
  "KW_RETURN",
  "KW_PRINT",
  "INT_LIT",
  "FLOAT_LIT",
  "STR_LIT",
  "ID"
  };
}

